services: docker

env:
  - distro: centos7
  - distro: debian7
  - distro: debian8
  - distro: debian9

script:

  # Download test script
  - wget -O ${PWD}/tests/test-ansible-role.sh https://gist.githubusercontent.com/samdoran/c3d392ee697881fa33a1d1a65814a07b/raw
  - chmod +x ${PWD}/tests/test-ansible-role.sh

  # Run tests
  - ${PWD}/tests/test-ansible-role.sh -d $distro

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
