- include_vars: RedHat.yml

- name: YUM | Add Docker repositories
  yum_repository:
    file: "{{ docker_repo_file }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
  loop: "{{ docker_yum_repositories[docker_edition | lower] }}"
  tags:
    - docker
    - yum
    - reposity
    - package

- name: YUM | Install Docker packages
  yum:
    name: "{{ docker_packages | union(docker_os_packages | default([])) }}"
    state: latest
  tags:
    - docker
    - yum
    - package

- name: YUM | Workaround for Docker 18.09
  include_tasks: docker-1809-workaround.yml
  when:
    - ansible_facts.virtualization_type == 'docker'
    - ansible_facts.service_mgr == 'systemd'

- name: YUM | Start and enable Docker
  service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: yes
  tags:
    - docker
    - service
